@uri=http://127.0.01:3000 

###
GET {{uri}}

### get natours API
GET https://www.natours.dev/api/v1/tours


###
POST {{uri}}



### Get all tours
GET {{uri}}/api/v1/tours






### Create a new Tour
POST {{uri}}/api/v1/tours
Content-Type: application/json

{
	"name": "Test Tour",
	"duration": 10,
	"difficulty": "easy"
}








### Get the specific tour that we picked this ID
GET {{uri}}/api/v1/tours/5



###
GET {{uri}}/api/v1/tours/7/23/45





### For Invalid ID, example
GET {{uri}}/api/v1/tours/23





### Update Tour
PATCH {{uri}}/api/v1/tours/3

Content-Type: application/json

{
	"duration": 15,
}





### Delete Tour
DELETE {{uri}}/api/v1/tours/7




### Get all users
GET {{uri}}/api/v1/users












### Create a new Tour,   For mutltiple middleware
POST {{uri}}/api/v1/tours
Content-Type: application/json

{
	"name": "Test Tour",
	"duration": 10,
	"difficulty": "easy",
	"price": 697
}









### Create a new Tour,   For another way to create a new document
POST {{uri}}/api/v1/tours
Content-Type: application/json

{
	"name": "Test Tour 2",
	"duration": 5,
	"difficulty": "easy",
	"price": 100,
	"rating": 4.7
}








### Create a new Tour,   test for errors
POST {{uri}}/api/v1/tours
Content-Type: application/json

{
	"name": "Tim Tour"
}










### get one tour
GET {{uri}}/api/v1/tours/5e02bdd974660d29def6b58c












### Update Tour
PATCH  {{uri}}/api/v1/tours/5e0297bf36bf9d0cbcce2d58

Content-Type: application/json

{
	"price": "some price"
}



### Delete Tour, delete a tour from mongoDB 
DELETE {{uri}}/api/v1/tours/5e03d94147bd90648127b923








### Create a new Tour
POST {{uri}}/api/v1/tours

Content-Type: application/json
{
    "name": "The Snow Adventurer",
    "duration": 4,
    "maxGroupSize": 10,
    "difficulty": "difficult",
    "ratingsAverage": 4.5,
    "ratingsQuantity": 13,
    "price": 997,
    "summary": "Exciting adventure in the snow with snowboarding and skiing",
    "description": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua, ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum!\nDolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, exercitation ullamco laboris nisi ut aliquip. Lorem ipsum dolor sit amet, consectetur adipisicing elit!",
    "imageCover": "tour-3-cover.jpg",
    "images": ["tour-3-1.jpg", "tour-3-2.jpg", "tour-3-3.jpg"],
    "startDates": ["2022-01-05,10:00", "2022-02-12,10:00", "2023-01-06,10:00"]
}